using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "eee34edc09f5785c")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Article</summary>
	[PublishedContentModel("article")]
	public partial class Article : PublishedContentModel, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "article";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Article(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Article, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("articleBanner")]
		public IPublishedContent ArticleBanner
		{
			get { return this.GetPropertyValue<IPublishedContent>("articleBanner"); }
		}

		///<summary>
		/// Banner Alt
		///</summary>
		[ImplementPropertyType("articleBannerAlt")]
		public string ArticleBannerAlt
		{
			get { return this.GetPropertyValue<string>("articleBannerAlt"); }
		}

		///<summary>
		/// Banner Title
		///</summary>
		[ImplementPropertyType("articleBannerTitle")]
		public string ArticleBannerTitle
		{
			get { return this.GetPropertyValue<string>("articleBannerTitle"); }
		}

		///<summary>
		/// Body
		///</summary>
		[ImplementPropertyType("articleBody")]
		public IHtmlString ArticleBody
		{
			get { return this.GetPropertyValue<IHtmlString>("articleBody"); }
		}

		///<summary>
		/// Image in list
		///</summary>
		[ImplementPropertyType("articleIcon")]
		public IEnumerable<IPublishedContent> ArticleIcon
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("articleIcon"); }
		}

		///<summary>
		/// PublishedDate
		///</summary>
		[ImplementPropertyType("articlePublishedDate")]
		public DateTime ArticlePublishedDate
		{
			get { return this.GetPropertyValue<DateTime>("articlePublishedDate"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("articleTitle")]
		public IHtmlString ArticleTitle
		{
			get { return this.GetPropertyValue<IHtmlString>("articleTitle"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Image Alt
		///</summary>
		[ImplementPropertyType("bannerImageAlt")]
		public string BannerImageAlt
		{
			get { return this.GetPropertyValue<string>("bannerImageAlt"); }
		}

		///<summary>
		/// Banner Image Title
		///</summary>
		[ImplementPropertyType("bannerImageTitle")]
		public string BannerImageTitle
		{
			get { return this.GetPropertyValue<string>("bannerImageTitle"); }
		}

		///<summary>
		/// Banner link
		///</summary>
		[ImplementPropertyType("bannerLink")]
		public string BannerLink
		{
			get { return this.GetPropertyValue<string>("bannerLink"); }
		}

		///<summary>
		/// Footer Images
		///</summary>
		[ImplementPropertyType("footerImages")]
		public IEnumerable<IPublishedContent> FooterImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("footerImages"); }
		}

		///<summary>
		/// Footer Images
		///</summary>
		[ImplementPropertyType("footerImagesList")]
		public IEnumerable<IPublishedContent> FooterImagesList
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("footerImagesList"); }
		}

		///<summary>
		/// Gallery Images
		///</summary>
		[ImplementPropertyType("galleryImages")]
		public IEnumerable<IPublishedContent> GalleryImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("galleryImages"); }
		}

		///<summary>
		/// Header Images
		///</summary>
		[ImplementPropertyType("headerImages")]
		public IEnumerable<IPublishedContent> HeaderImages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("headerImages"); }
		}

		///<summary>
		/// Banner
		///</summary>
		[ImplementPropertyType("mainBanner")]
		public IPublishedContent MainBanner
		{
			get { return this.GetPropertyValue<IPublishedContent>("mainBanner"); }
		}

		///<summary>
		/// Page Body
		///</summary>
		[ImplementPropertyType("pageBody")]
		public IHtmlString PageBody
		{
			get { return this.GetPropertyValue<IHtmlString>("pageBody"); }
		}

		///<summary>
		/// Top logo
		///</summary>
		[ImplementPropertyType("topLogo")]
		public IEnumerable<IPublishedContent> TopLogo
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("topLogo"); }
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Casinos</summary>
	[PublishedContentModel("casinos")]
	public partial class Casinos : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "casinos";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Casinos(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Casinos, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Sportsbetting</summary>
	[PublishedContentModel("sportsbetting")]
	public partial class Sportsbetting : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sportsbetting";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Sportsbetting(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Sportsbetting, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>History OCM</summary>
	[PublishedContentModel("historyOCM")]
	public partial class HistoryOcm : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "historyOCM";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HistoryOcm(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HistoryOcm, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Operators</summary>
	[PublishedContentModel("operators")]
	public partial class Operators : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "operators";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Operators(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Operators, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Providers</summary>
	[PublishedContentModel("providers")]
	public partial class Providers : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "providers";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Providers(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Providers, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Reviews</summary>
	[PublishedContentModel("reviews")]
	public partial class Reviews : PublishedContentModel, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "reviews";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Reviews(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Reviews, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Tips</summary>
	[PublishedContentModel("tips")]
	public partial class Tips : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tips";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Tips(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Tips, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Slot Machines</summary>
	[PublishedContentModel("slotMachines")]
	public partial class SlotMachines : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slotMachines";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SlotMachines(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlotMachines, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Contact</summary>
	[PublishedContentModel("contact")]
	public partial class Contact : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contact";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Contact(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Contact, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>XMLSitemap</summary>
	[PublishedContentModel("xMLSitemap")]
	public partial class XMlsitemap : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "xMLSitemap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public XMlsitemap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<XMlsitemap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}
	}

	/// <summary>Carousel Slide</summary>
	[PublishedContentModel("carouselSlide")]
	public partial class CarouselSlide : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselSlide";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselSlide(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselSlide, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Slide Image
		///</summary>
		[ImplementPropertyType("slideImage")]
		public IPublishedContent SlideImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("slideImage"); }
		}

		///<summary>
		/// Slide Image alt
		///</summary>
		[ImplementPropertyType("slideImageAlt")]
		public string SlideImageAlt
		{
			get { return this.GetPropertyValue<string>("slideImageAlt"); }
		}

		///<summary>
		/// Slide Image title
		///</summary>
		[ImplementPropertyType("slideImageTitle")]
		public string SlideImageTitle
		{
			get { return this.GetPropertyValue<string>("slideImageTitle"); }
		}

		///<summary>
		/// Slide Link
		///</summary>
		[ImplementPropertyType("slideLink")]
		public string SlideLink
		{
			get { return this.GetPropertyValue<string>("slideLink"); }
		}

		///<summary>
		/// Slide Subtitle
		///</summary>
		[ImplementPropertyType("slideSubtitle")]
		public string SlideSubtitle
		{
			get { return this.GetPropertyValue<string>("slideSubtitle"); }
		}

		///<summary>
		/// Slide Title
		///</summary>
		[ImplementPropertyType("slideTitle")]
		public string SlideTitle
		{
			get { return this.GetPropertyValue<string>("slideTitle"); }
		}

		///<summary>
		/// Disabled
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}

	// Mixin content Type 1193 with alias "seo"
	/// <summary>Seo</summary>
	public partial interface ISeo : IPublishedContent
	{
		/// <summary>Description</summary>
		string SeoDescription { get; }

		/// <summary>Keywords</summary>
		string SeoKeywords { get; }

		/// <summary>Title</summary>
		string SeoTitle { get; }
	}

	/// <summary>Seo</summary>
	[PublishedContentModel("seo")]
	public partial class Seo : PublishedContentModel, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "seo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Seo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Seo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return GetSeoDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetSeoDescription(ISeo that) { return that.GetPropertyValue<string>("seoDescription"); }

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return GetSeoKeywords(this); }
		}

		/// <summary>Static getter for Keywords</summary>
		public static string GetSeoKeywords(ISeo that) { return that.GetPropertyValue<string>("seoKeywords"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return GetSeoTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetSeoTitle(ISeo that) { return that.GetPropertyValue<string>("seoTitle"); }
	}

	/// <summary>Robot</summary>
	[PublishedContentModel("robot")]
	public partial class Robot : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "robot";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Robot(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Robot, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return this.GetPropertyValue<string>("content"); }
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}
	}

	/// <summary>Casino</summary>
	[PublishedContentModel("casino")]
	public partial class Casino : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "casino";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Casino(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Casino, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("casinoDescription")]
		public IHtmlString CasinoDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("casinoDescription"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("casinoImage")]
		public IPublishedContent CasinoImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("casinoImage"); }
		}

		///<summary>
		/// Image Alt
		///</summary>
		[ImplementPropertyType("casinoImageAlt")]
		public string CasinoImageAlt
		{
			get { return this.GetPropertyValue<string>("casinoImageAlt"); }
		}

		///<summary>
		/// Image Title
		///</summary>
		[ImplementPropertyType("casinoImageTitle")]
		public string CasinoImageTitle
		{
			get { return this.GetPropertyValue<string>("casinoImageTitle"); }
		}

		///<summary>
		/// Rating
		///</summary>
		[ImplementPropertyType("casinoRating")]
		public decimal CasinoRating
		{
			get { return this.GetPropertyValue<decimal>("casinoRating"); }
		}

		///<summary>
		/// Rating2
		///</summary>
		[ImplementPropertyType("casinoRating2")]
		public decimal CasinoRating2
		{
			get { return this.GetPropertyValue<decimal>("casinoRating2"); }
		}

		///<summary>
		/// Register
		///</summary>
		[ImplementPropertyType("casinoRegister")]
		public string CasinoRegister
		{
			get { return this.GetPropertyValue<string>("casinoRegister"); }
		}

		///<summary>
		/// Register Link
		///</summary>
		[ImplementPropertyType("casinoRegisterLink")]
		public string CasinoRegisterLink
		{
			get { return this.GetPropertyValue<string>("casinoRegisterLink"); }
		}

		///<summary>
		/// Review
		///</summary>
		[ImplementPropertyType("casinoReview")]
		public string CasinoReview
		{
			get { return this.GetPropertyValue<string>("casinoReview"); }
		}

		///<summary>
		/// Review Link
		///</summary>
		[ImplementPropertyType("casinoReviewLink")]
		public string CasinoReviewLink
		{
			get { return this.GetPropertyValue<string>("casinoReviewLink"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("casinoTitle")]
		public string CasinoTitle
		{
			get { return this.GetPropertyValue<string>("casinoTitle"); }
		}
	}

	/// <summary>Custom Image</summary>
	[PublishedContentModel("customImage")]
	public partial class CustomImage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customImage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomImage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomImage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Alt
		///</summary>
		[ImplementPropertyType("customAlt")]
		public string CustomAlt
		{
			get { return this.GetPropertyValue<string>("customAlt"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("customMediaImage")]
		public IPublishedContent CustomMediaImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("customMediaImage"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("customTitle")]
		public string CustomTitle
		{
			get { return this.GetPropertyValue<string>("customTitle"); }
		}
	}

	/// <summary>Affiliate Programs</summary>
	[PublishedContentModel("affiliatePrograms")]
	public partial class AffiliatePrograms : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "affiliatePrograms";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AffiliatePrograms(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AffiliatePrograms, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	// Mixin content Type 1389 with alias "basePage"
	/// <summary>Base Page</summary>
	public partial interface IBasePage : IPublishedContent
	{
		/// <summary>Disabled in menu</summary>
		bool DisabledInMenu { get; }
	}

	/// <summary>Base Page</summary>
	[PublishedContentModel("basePage")]
	public partial class BasePage : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "basePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return GetDisabledInMenu(this); }
		}

		/// <summary>Static getter for Disabled in menu</summary>
		public static bool GetDisabledInMenu(IBasePage that) { return that.GetPropertyValue<bool>("disabledInMenu"); }
	}

	/// <summary>XMLSitemapRoot</summary>
	[PublishedContentModel("xMLSitemapRoot")]
	public partial class XMlsitemapRoot : PublishedContentModel, IBasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "xMLSitemapRoot";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public XMlsitemapRoot(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<XMlsitemapRoot, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}
	}

	/// <summary>Sports</summary>
	[PublishedContentModel("sports")]
	public partial class Sports : PublishedContentModel, IBasePage, ISeo
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sports";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Sports(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Sports, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled in menu
		///</summary>
		[ImplementPropertyType("disabledInMenu")]
		public bool DisabledInMenu
		{
			get { return Umbraco.Web.PublishedContentModels.BasePage.GetDisabledInMenu(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoDescription(this); }
		}

		///<summary>
		/// Keywords
		///</summary>
		[ImplementPropertyType("seoKeywords")]
		public string SeoKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoKeywords(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return Umbraco.Web.PublishedContentModels.Seo.GetSeoTitle(this); }
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Alt: Alternative image text
		///</summary>
		[ImplementPropertyType("alt")]
		public string Alt
		{
			get { return this.GetPropertyValue<string>("alt"); }
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
